GET localhost:8080/member/1

###
POST localhost:8080/member
content-type: application/json

{
    "age":18,
    "name":"mark"
}
###
PUT localhost:8080/member/1

###
PATCH localhost:8080/member/1

###
DELETE localhost:8080/member/1
